server:
  port: 8081


# ******** POSTGRESQL CONFIGURATION ********
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dgs
    username: dgs
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  devtools:
    restart:
      enabled: false


# ******** MYSQL CONFIGURATION ********
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/dgs
#    username: dgs
#    password: mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        enable_lazy_load_no_trans: true
#  devtools:
#    restart:
#      enabled: false