spring:
  application:
    name: dgs-example-java

logging:
  level:
    io.micrometer.core.instrument.logging: INFO

debug: true

---
spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
